blog/urls.py
from django.urls import path
from . import views
from .views import CategoryListView, BlogCategoryList, CategoriesListView, CommentCreate, SearchListView

app_name='blog'

urlpatterns = [
    path('',views.CategoryListView.as_view(), name='top'),
    path('categories/<int:pk>/',views.BlogCategoryList.as_view(),name='category_list'),
    path('categories/',views.CategoriesListView.as_view(),name='categories'),
    path('detail/<int:pk>/',views.detail,name='blog_detail'),
    # path('detail/<int:pk>/like/',views.like,name="like"),
    # path('api/like/<int:pk>/', views.api_like, name="api_like"),
    path('create/',views.blog_create,name='blog_create'),
    path('comment/<int:pk>/',views.CommentCreate.as_view(),name='comment_create'),
    path('search/',views.SearchListView.as_view(),name='search'),
    path('recommend/',views.RecommendListView.as_view(),name='recommend'),
]

fractalsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here.



class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('タグ', max_length=50)

    def __str__(self):
        return self.name

class Blog(models.Model):
    category = models.ForeignKey(Category,verbose_name='カテゴリ',on_delete=models.PROTECT,related_name='blogs')
    writer = models.CharField('投稿者',max_length=255,default="名無しさん")
    title = models.CharField('記事タイトル',max_length=255)
    text = models.TextField('記事本文',blank=False)
    created_at = models.DateTimeField('作成日',default=timezone.now)
    views = models.PositiveIntegerField(default=0)
    tag = models.ManyToManyField(Tag, verbose_name='タグ',related_name='blogs')
    # like = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Comment(models.Model):
    commenter = models.CharField('ニックネーム',max_length=255,default="名無しさん")
    text = models.TextField('コメント')
    target = models.ForeignKey(Blog,on_delete=models.PROTECT, verbose_name="対象記事")
    created_at = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return self.text[:999]

blog/forms.py
from django import forms
from .models import Blog, Comment, Category

class BlogCreateForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = '__all__'

class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('commenter','text',)
        widgets = {
            'text': forms.Textarea(attrs={'class':'textarea'})
        }

class PostSearchForm(forms.Form):
    key_word = forms.CharField(
        label='キーワードや投稿者', required=False,
        widget=forms.TextInput(attrs={'class': 'input'})
    )
    category = forms.ModelChoiceField(
        label='カテゴリの選択', required=False,
        queryset=Category.objects.all(),
    )

blog/views.py
from django.http import HttpResponse, Http404
from django.views import generic
from .models import Blog, Category, Comment, Tag
from django.shortcuts import render, get_object_or_404, redirect
from .forms import BlogCreateForm, CommentCreateForm, PostSearchForm
from django.db.models import Q
from django.http.response import JsonResponse
from django.contrib import messages
from functools import reduce
from operator import and_


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'blog/top.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['blog_views'] = Blog.objects.order_by('-views')[:4]
        ctx['tag_list'] = Tag.objects.all()[:1]
        return ctx



class CategoriesListView(generic.ListView):
    model = Category
    template_name = 'blog/categories.html'
    paginate_by=8

    def categories(request,id):
        context = {
            'categories': Category.objects.all(),
            'blog_list': Blog.objects.filter(category_id=id),
            }
        return render(request, 'blog/categories.html',context)


class BlogCategoryList(generic.ListView):
    model = Blog
    ordering = '-created_at'
    template_name = 'blog/category_list.html'
    paginate_by=8

    def get_queryset(self):
        category = get_object_or_404(Category,pk=self.kwargs['pk'])
        return super().get_queryset().filter(category=category)


def detail(request,pk):
    try:
        blog = Blog.objects.get(pk=pk)
    except Blog.DoesNotExist:
        raise Http404

    context = {
        'blog':blog,
    }
    blog.views += 1
    blog.save()
    return render(request, 'blog/blog_detail.html', context)


def blog_create(request):
    form = BlogCreateForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('blog:top')

    context={
        'form':form,
    }
    return render(request, 'blog/blog_create.html', context)


class CommentCreate(generic.CreateView):
    model=Comment
    form_class=CommentCreateForm

    def form_valid(self,form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Blog,pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        return redirect('blog:blog_detail',pk=post_pk)

class SearchListView(generic.ListView):
    model = Blog
    ordering = '-created_at'
    template_name = 'blog/search.html'
    paginate_by=8

    def blogs(request):
        context = {
            'blog_list': Blog.objects.all(),
            }
        return render(request, 'blog/search.html',context)

    def get_queryset(self):
        queryset = Blog.objects.order_by('-id')
        keyword = self.request.GET.get('keyword')
        if keyword:
            exclusion = set([' ', '　'])
            q_list = ''
            for i in keyword:
                if i in exclusion:
                    pass
                else:
                    q_list += i
            query = reduce(
                and_, [Q(title__icontains=q) | Q(text__icontains=q) for q in q_list]
            )
            queryset = queryset.filter(query)
            messages.success(self.request, '「{}」の検索結果'.format(keyword))

    # def get_queryset(self):
    #     queryset=super().get_queryset()
    #     form=PostSearchForm(self.request.GET or None)
    #     if form.is_valid():
    #         key_word=form.cleaned_data.get('key_word')
    #         if key_word:
    #             queryset=queryset.filter(Q(title__icontains=key_word)|Q(text__icontains=key_word))

            # category=form.cleaned_data.get('category')
            # if category:
            #     queryset=queryset.filter(category=category)

        return queryset

# def like(request,pk):
#     try:
#         blog = Blog.objects.get(pk=pk)
#     except Blog.DoesNotExist:
#         raise Http404
#     blog.like += 1
#     blog.save()
#     return redirect('blog:blog_detail',pk)

# def api_like(request,pk):
#     try:
#         blog = Blog.objects.get(pk=pk)
#     except Blog.DoesNotExist:
#         raise Http404
#     blog.like += 1
#     blog.save()
#     return JsonResponse({"like":blog.like})

class RecommendListView(generic.ListView):
    model = Blog
    template_name = 'blog/recommend.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['blog_views'] = Blog.objects.order_by('-views')
        return ctx

blog/templates/blog/base.html
{% load static %}
{% load sass_tags %}
<!DOCTYPE html>
{% load blog %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% sass_src 'blog/style.scss' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'blog/main.js' %}"></script>
  </head>
  <header>
    <div class="nav-button">
      <span></span>
      <span></span>
    </div>
    <a href="{% url 'blog:top' %}" class="header-logo"></a>
  </header>
  <div class="nav-menu">
    <a href="{% url 'blog:top' %}" class="menu-logo"></a>
    {% create_search_form request %}
    <a href="{% url 'blog:categories' %}" class="menu-link">カテゴリ一覧</a><br>
    <a href="{% url 'blog:recommend' %}" class="menu-link">オススメ</a><br>
    <a href="{% url 'blog:blog_create' %}" class="menu-link">記事投稿</a>
  </div>
  <body>
    {% block content %}{% endblock %}
  </body>
  <footer>
    <div class="large-footer">
      <a href="{% url 'blog:top' %}" class="footer-logo"></a>
      <div class="footer-nav">
        <div class="footer-nav1">
          <a href="{% url 'blog:categories' %}" class="menu-link">カテゴリ一覧</a><br>
          <a href="{% url 'blog:recommend' %}" class="menu-link">オススメ</a><br>
          <a href="{% url 'blog:blog_create' %}" class="menu-link">記事投稿</a>
        </div>
        <div class="footer-nav2">
          <a href="https://fractalfrgmts.com/%e3%81%8a%e5%95%8f%e3%81%84%e5%90%88%e3%82%8f%e3%81%9b/" target="_blank" class="menu-link">お問い合わせ</a><br>
          <a href="https://fractalfrgmts.com/" target="_blank" class="menu-link">事業内容</a><br>
          <a href="https://fractalfrgmts.com/%e4%bc%9a%e7%a4%be%e6%a6%82%e8%a6%81/" target="_blank" class="menu-link">会社概要</a>
        </div>
      </div>
    </div>
    <p class="copyright">Fractal Copyright Allrights Reserved</p>
  </footer>
</html>

blog/templates/blog/blog_create.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<section class="create-page">
  <div class="create-container">
    <h1>記事の投稿</h1>
    <form class="blog_create" action="" method="post">
      {{ form.non_field_errors }}
      {% for field in form %}
      <div class="field">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
            <span class="helptext">{{ field.help_text }}</span>
        {% endif %}
        {{ field.errors }}
      </div>
      {% endfor %}
      {% csrf_token %}
      <button type="submit"><p>この内容で投稿</p></button>
    </form>
  </div>
</section>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<section class="detail-page">
  <div class="detail-container">
    <article>
      <div class="art-subinfo">
        <div class="category-box">
          <p>{{blog.category}}</p>
        </div>
        <p class="art-writer">投稿者:{{blog.writer}}</p>
      </div>
        <h1>{{blog.title}}</h1>
        <!-- <div class="ad"><p>広告</p></div> -->
        <div class="blog-text">
          {{blog.text | linebreaks | urlize}}
        </div>
        <div class="blog-afterinfo">
          <p class="art-date">{{blog.created_at}}</p>
          <p>{{ blog.views }}PV</p>
        </div>
    </article>
    <!-- <p><a onclick="api_like()"><span id="like">{{ blog.like }}</span>いいね！</a></p> -->
    <a class="another-art" href="{% url 'blog:categories' %}"><p>他の記事を探す</p></a>
    <!-- {% if page_obj.has_previous %}
      <a href="{% url 'blog:blog_detail' older_article.pk %}">前の記事</a>
    {% endif %}
    {% if page_obj.has_next %}
      <a href="{% url 'blog:blog_detail' newer_article.pk %}">次の記事</a>
    {% endif %} -->
    <a class="button is-primary" href="{% url 'blog:comment_create' blog.pk %}"><p>コメントする</p></a>
    <!-- <div class="ad"><p>広告</p></div> -->
  </div>
</section>
<section class="comment">
  <h2>コメント</h2>
  {% for comment in blog.comment_set.all %}
    <div class="each-comment">
      <p class="commenter">{{ comment.commenter }}</p>
      <p class="comment-content">{{ comment | linebreaks | urlize }}</p>
      <p class="comment-date">{{comment.created_at}}</p>
    </div>
  {% empty %}
    <p>コメントはまだありません</p>
  {% endfor %}
</section>
{% endblock %}

blog/templates/blog/blog_list.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>カテゴリ内記事一覧</h1>
    <p>{{ blog.category }}</p>
    {% for blog in blog_list %}
    <article>
      <h2>{{ blog.title }}</h2>
    </article>
    {% endfor %}
  </body>
</html>

blog/templates/blog/categories.html
{% extends 'blog/base.html' %}
{% block content %}
<section class="categories-page">
  <div class="categories-content-container">
    <h1>カテゴリ一覧</h1>
    {% for category in object_list %}
      <div class="each-category-content">
        <div class="each-category-box">
          <p>{{category.name}}</p>
        </div>
        <div class="article-flex">
        {% for blog in category.blogs.all|slice:":2" %}
        <a href="{% url 'blog:blog_detail' blog.pk %}" class="article">
          <p class="art-date">{{ blog.created_at }}</p>
          <p class="art-views">{{ blog.views }}PV</p>
          <p class="art-title">{{ blog.title}}</p>
          <!-- {{ blog.like }}Likes  -->
        </a>
        {% endfor %}
        </div>
        <a class="to-category-detail" href="{% url 'blog:category_list' category.pk %}"><p>このカテゴリをもっと見る</p></a>
      </div>
    {% endfor %}
    <div class="for-flex">
      {% if page_obj.has_previous %}
        <a class="left-arrow-a" href="?page={{page_obj.previous_page_number }}"></a>
      {% endif %}
        <p class="page-number">{{page_obj.number}}</p>
      {% if page_obj.has_next %}
        <a class="right-arrow-a" href="?page={{page_obj.next_page_number }}"></a>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% block content %}
<section class="category-list-page">
  <div class="category-list-container">
    <h1>カテゴリ内記事一覧</h1>
        <div class="each-category-content">
          <div class="each-category-box">
            {% for blog in blog_list|slice:":1" %}
            <p>{{ blog.category }}</p>
            {% endfor %}
          </div>
          <div class="article-flex">
            {% for blog in blog_list %}
            <a href="{% url 'blog:blog_detail' blog.pk %}" class="article">
              <p class="art-date">{{ blog.created_at }}</p>
              <p class="art-views">{{ blog.views }}PV</p>
              <p class="art-title">{{ blog.title}}</p>
              <!-- {{ blog.like }}Likes  -->
            </a>
            {% endfor %}
          </div>
        </div>
        <div class="for-flex">
          {% if page_obj.has_previous %}
            <a class="left-arrow-a" href="?page={{page_obj.previous_page_number }}"></a>
          {% endif %}
            <p class="page-number">{{page_obj.number}}</p>
          {% if page_obj.has_next %}
            <a class="right-arrow-a" href="?page={{page_obj.next_page_number }}"></a>
          {% endif %}
        </div>
      <a class="back-to-category-list" href="{% url 'blog:categories' %}"><p>カテゴリ一覧へ戻る</p></a>
  </div>
</section>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}
<section class="comment-page">
  <div class="comment-container">
    <h1>コメント投稿</h1>
    <form class="comment_create" action="" method="post">
      {{ form.non_field_errors }}
      {% for field in form %}
      <div class="field">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
            <span class="helptext">{{ field.help_text }}</span>
        {% endif %}
        {{ field.errors }}
      </div>
      {% endfor %}
      {% csrf_token %}
      <button type="submit" name="button"><p>投稿</p></button>
    </form>
  </div>
</section>
{% endblock %}

blog/templates/blog/recommend.html
{% extends 'blog/base.html' %}
{% block content %}
<section class="recommend-page">
  <div class="recommend-container">
    <h1>オススメ記事</h1>
    <div class="each-category-content">
      <div class="article-flex">
      {% for blog in blog_views|slice:":10" %}
      <a href="{% url 'blog:blog_detail' blog.pk %}" class="article">
        <p class="art-date">{{ blog.created_at }}</p>
        <p class="art-views">{{ blog.views }}PV</p>
        <p class="art-title">{{ blog.title}}</p>
        <!-- {{ blog.like }}Likes  -->
      </a>
      {% endfor %}
      </div>
    </div>
    <a class="back-to-category-list" href="{% url 'blog:categories' %}"><p>カテゴリ一覧へ</p></a>
  </div>
</section>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% block content %}
<section class="search-page">
  <div class="search-container">
    <h1>検索結果</h1>
    <div class="each-category-content">
      <div class="article-flex">
      {% if blog_list %}
      {% for blog in blog_list %}
      <a href="{% url 'blog:blog_detail' blog.pk %}" class="article">
        <div class="art-category-box">
          <p class="art-category">{{ blog.category }}</p>
        </div>
        <p class="art-date">{{ blog.created_at }}</p>
        <h2 class="art-title">{{ blog.title}}</h2>
        <!-- {{ blog.like }}Likes -->
      </a>
      {% endfor %}
      </div>
      {% else %}
        <p class="no-result">検索結果はありません。</p>
      {% endif %}
    </div>
    <div class="for-flex">
      {% if page_obj.has_previous %}
        <a class="left-arrow-a" href="?page={{page_obj.previous_page_number }}"></a>
      {% endif %}
        <p class="page-number">{{page_obj.number}}</p>
      {% if page_obj.has_next %}
        <a class="right-arrow-a" href="?page={{page_obj.next_page_number }}"></a>
      {% endif %}
    </div>
    <p class="page-total-number">of {{ page_obj.paginator.num_pages }}</p>
  </div>
</section>
{% endblock %}

blog/templates/blog/search_form.html
<p class="search-fractal">フラクタルを検索</p>

<!-- <form action="{% url 'blog:search' %}" method="GET">
  <div class="field">
    <div class="control">
      {{ form.key_word }}
    </div>
  </div>
  <div class="field">
    <div class="control">
      <div class="select">
        {{ form.category }}
      </div>
    </div>
  </div>
  <button type="submit">検索</button>
</form> -->

<form method="GET" action="{% url 'blog:search' %}">
  <input type="text" name="keyword">
  <button type="submit">検索</button>
</form>

blog/templates/blog/top.html
{% extends 'blog/base.html' %}
{% block content %}
  <section class="top-page">
    <div class="top-news">
      <div class="top-news-container">
        <p class="top-news-text">トップニュース</p>
        <div class="article-flex">
          {% for tag in tag_list|slice:":1" %}
            {% for blog in tag.blogs.all|slice:":1" %}
            <a href="{% url 'blog:blog_detail' blog.pk %}" class="article">
              <div class="art-category-box">
                <p class="art-category">{{ tag.name }}</p>
              </div>
              <p class="art-date">{{ blog.created_at }}</p>
              <p class="art-views">{{ blog.views }}PV</p>
              <p class="art-title">{{ blog.title}}</p>
              <!-- {{ blog.like }}Likes  -->
            </a>
            {% endfor %}
          {% endfor %}
          {% for blog in blog_views|slice:":3" %}
            <a href="{% url 'blog:blog_detail' blog.pk %}" class="article">
              <div class="art-category-box">
                <p class="art-category">{{ blog.category }}</p>
              </div>
              <p class="art-date">{{ blog.created_at }}</p>
              <p class="art-views">{{ blog.views }}PV</p>
              <h2 class="art-title">{{ blog.title}}</h2>
              <!-- {{ blog.like }}Likes -->
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="top-content">
      <div class="top-content-container">
        {% for category in object_list|slice:":3"  %}
          <div class="each-category-content">
            <div class="each-category-box">
              <p>{{category.name}}</p>
            </div>
            <div class="article-flex">
              {% for blog in category.blogs.all|slice:":4" %}
              <a href="{% url 'blog:blog_detail' blog.pk %}" class="article">
                <p class="art-date">{{ blog.created_at }}</p>
                <p class="art-views">{{ blog.views }}PV</p>
                <p class="art-title">{{ blog.title}}</p>
                <!-- {{ blog.like }}Likes  -->
              </a>
              {% endfor %}
            </div>
            <a class="to-category-detail" href="{% url 'blog:category_list' category.pk %}"><p>このカテゴリをもっと見る</p></a>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}